before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
language: java
jdk: openjdk11
sudo: false
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
    mvn --settings .maven.xml clean verify -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
## Build and release to maven central
script:
    mvn --settings .maven.xml clean deploy -DskipTests=true -B -U -Prelease
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  # Set up git user name and tag this commit
  - git config --local user.name "$GH_NAME"
  - git config --local user.email "$GH_MAIL"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$project_version-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    api_key: "$GH_TOKEN"
    file: 
      - target/fx-dnd-layout-$project_version.jar
      - target/fx-dnd-layout-$project_version-sources.jar
    skip_cleanup: true
    on:
      repo: PSI-Polska/fx-dnd-layout
name: $project_version