before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
language: java
jdk: openjdk11
sudo: false
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
    mvn --settings .maven.xml clean verify -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
after_install:
    export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[' | tail -n 1);
    export is_snapshot=$(echo $project_version | grep SNAPSHOT);
    if [ $is_snapshot ];
      then export TRAVIS_TAG=${TRAVIS_TAG:-$project_version-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)};
      else export TRAVIS_TAG=${TRAVIS_TAG:-$project_version};
    fi
    # Set up git user name and tag this commit
    if git rev-parse "$TRAVIS_TAG" >/dev/null 2>&1;
      then export is_already_deployed=true;
    fi
    if [ "$is_already_deployed" = true ];
      then echo "Release $TRAVIS_TAG was already deployed, skipping deploy.";
      else echo "Creating tag for $TRAVIS_TAG release as deployment preparation.";
      git config --local user.name "$GH_NAME";
      git config --local user.email "$GH_MAIL";
      git tag $TRAVIS_TAG;
    fi
    if ! [ "$is_snapshot" = true ] && ! [ "$is_already_deployed" = true ];
      then export SHOULD_RUN_DEPLOY=true;
    fi
deploy:
  - provider: script
    name: $project_version
    ## Build and release to maven central
    script: mvn --settings .maven.xml clean deploy -DskipTests=true -B -U -Prelease
    skip_cleanup: true
    on:
      condition: "$SHOULD_RUN_DEPLOY"
  - provider: releases
    name: $project_version
    prerelease: false
    api_key: "$GH_TOKEN"
    file: 
      - target/fx-dnd-layout-$project_version.jar
      - target/fx-dnd-layout-$project_version-sources.jar
    skip_cleanup: true
    on:
      repo: PSI-Polska/fx-dnd-layout
      condition: "$SHOULD_RUN_DEPLOY"
  # - provider: releases 
  #   name: $project_version
  #   prerelease: true
  #   api_key: "$GH_TOKEN"
  #   file: 
  #     - target/fx-dnd-layout-$project_version.jar
  #     - target/fx-dnd-layout-$project_version-sources.jar
  #   skip_cleanup: true
  #   on:
  #     repo: PSI-Polska/fx-dnd-layout
  #     condition: "$is_snapshot"